### ISSUE TITLE
Question about UTPSocket::cur_window_packets initialization.

### ISSUE THREAD

**Issue by freak82** [bittorrent/libutp#119]
Hi there,

There is a member variable in UTPSocket
```
uint16 cur_window_packets;
```
which doesn't seem to be initialized anywhere.
I tried to search for `memset` or for `cur_window_packets =` smth, but couldn't find any such expression which sets this variable to some value. I see that it's increased, decreased and compared, though.

I'm using the source code from the master branch. What I'm missing?

Thanks,
Pavel.

**Comment by IvanKuzavkov** [comment]
Hello,
It's because of formatting in function:
```C
utp_socket*	utp_create_socket(utp_context *ctx)
```
if you look inside you can find initialization of this variable.

**Comment by freak82** [comment]
I see. Thanks.
